name: Production deployment workflow

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to snake.lukamaret.com
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'cd /var/www/snake.lukamaret.com &&
            git checkout main &&
            git pull'
